name: Deploy Django Application to Render

on:
  push:
    branches:
      - main  # This will trigger the workflow when you push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # The job will run on an Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checkout your repository

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Setup Docker Buildx for building multi-platform images

    - name: Set up Docker
      uses: docker/setup-qemu-action@v2  # Setup QEMU to build Docker images

    - name: Log in to DockerHub
      uses: docker/login-action@v2  # Login to Docker Hub using your secrets
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # GitHub secret for your Docker Hub username
        password: ${{ secrets.DOCKER_PASSWORD }}  # GitHub secret for your Docker Hub password (or token)

    - name: Build and push Docker image
      run: |
        docker build -t your-docker-repo/your-app-name .
        docker push your-docker-repo/your-app-name  # Push the image to Docker Hub

    - name: Deploy to Render
      run: |
        git remote add render https://git@github.com/your-username/your-repository.git
        git push render main  # Push changes to Render for deployment
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
