name: Deploy Django Application to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  

    - name: Install dependencies
      run: |
        pip install --upgrade pip  # Upgrade pip to avoid any version issues
        pip install -r requirements.txt  # Install the dependencies

    - name: Run migrations and collect static files
      run: |
        python manage.py migrate  # Apply migrations
        python manage.py collectstatic --noinput  # Collect static files
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}  
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}

    - name: Deploy to Render
      run: |
        git remote add render https://git@github.com/<your-username>/<your-repository>.git
        git push render main  # Push the changes to Render
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
