name: Deploy Django Application to Render

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  

    - name: Install dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run migrations and collect static files
      run: |
        source venv/bin/activate
        python3 manage.py migrate  # Run database migrations
        python3 manage.py collectstatic --noinput  # Collect static files

    - name: Deploy to Render
      run: |
        git remote add render https://git@github.com/<your-username>/<your-repository>.git
        git push render main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
