name: Deploy Django Application to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker
      uses: docker/setup-qemu-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t belam443/blogiz-web .
        docker push belam443/blogiz-web



    - name: Deploy to Render
      run: |
        # Add render remote to git
        git remote add render https://github.com/bmuia/blogiz.git
        
        # Set up Git credentials using the PAT
        git config --global credential.helper store
        echo "https://${{ secrets.RENDER_PAT }}@github.com" > ~/.git-credentials


      - name: Debug Git Configuration
        run: |
           git config --list
           cat ~/.git-credentials

        
        # Push to the remote repository 
        git push render main

      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        GITHUB_TOKEN: ${{ secrets.RENDER_PAT }}
