name: Deploy Blog Application API to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.1

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Render CLI
      run: |
        # Download Render CLI directly from GitHub releases
        curl -L https://github.com/render-oss/cli/releases/download/v1.1.0/cli_1.1.0_linux_amd64.zip -o render.zip
        unzip render.zip
        sudo mv cli_v1.1.0 /usr/local/bin/render

    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}  #
      run: |
        render deploys create --service blogiz-1 --branch main  # Correct command to trigger deployment

    - name: Verify Deployment
      run: |
        curl --silent --fail https://blogiz-1.onrender.com || exit 1
