name: Deploy Blog Application API to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.1

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Render
      run: |
        # Set up Render CLI
        curl -sSL https://render.com/install | bash
        export PATH=$PATH:$HOME/.render/bin
        
        # Log in to Render CLI
        render login --api-key ${{ secrets.RENDER_API_KEY }}
        
        # Deploy your service (
        render deploy --service blogiz-1 --branch main

    # Optionally, you can also add a step to confirm that the deployment was successful
    - name: Verify Deployment
      run: |
        curl --silent --fail https://blogiz-1.onrender.com || exit 1
